window_options = [{'label': 'Modified Bartlett-Hann window', 'value': 'barthann'},
                  {'label': 'Bartlett window', 'value': 'bartlett'},
                  {'label': 'Blackman window', 'value': 'blackman'},
                  {'label': 'Minimum 4-term Blackman-Harris window', 'value': 'blackmanharris'},
                  {'label': 'Bohman window', 'value': 'bohman'},
                  {'label': 'Boxcar/rectangular window', 'value': 'boxcar'},
                  # {'label': 'Dolph-Chebyshev window', 'value': 'chebwin'},
                  {'label': 'Cosine shape window', 'value': 'cosine'},
                  # {'label': 'Compute the Discrete Prolate Spheroidal Sequences (DPSS)', 'value': 'dpss'},
                  # {'label': 'Poisson/exponential window', 'value': 'exponential'},
                  {'label': 'Flat top window', 'value': 'flattop'},
                  {'label': 'Gaussian window', 'value': 'gaussian'},
                  # {'label': 'Generic weighted sum of cosine terms window', 'value': 'general_cosine'},
                  # {'label': 'Window with generalized Gaussian shape', 'value': 'general_gaussian'},
                  # {'label': 'Generalized Hamming window', 'value': 'general_hamming'},
                  {'label': 'Hamming window', 'value': 'hamming'},
                  {'label': 'Hann window', 'value': 'hann'},
                  # {'label': 'Kaiser window', 'value': 'kaiser'},
                  {'label': 'Minimum 4-term Blackman-Harris window according to Nuttall', 'value': 'nuttall'},
                  {'label': 'Parzen window', 'value': 'parzen'},
                  {'label': 'Triangular window', 'value': 'triang'}
                  # {'label': 'Takey/tapered cosine window', 'value': 'tukey'},
                  ]
